### ISSUE TITLE
copy url only after creating link

### ISSUE THREAD

**Issue by changchichung** [Scribblerockerz/cryptletter#29]
After encrypting the message, the system currently selects the entire text (including the description and URL) by default.
![](https://i.imgur.com/gQDM6Vy.png)

is it able to select only the URL, or copy the URL to the clipboard?

**Comment by Scribblerockerz** [comment]
This is the default behavior.

To change it, you have 2 options:

- Change the translation for `messageResult` and remove the previous text.
- Update the template in [.../web/src/pages/LetterNew.vue](https://github.com/Scribblerockerz/cryptletter/blob/master/web/src/pages/LetterNew.vue) and build the frontend assets and bundle them up in your own executable.

**Comment by changchichung** [comment]
thanks , I will try to update the template.
